version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - cd client
      - npm install
      - npm run build
  build:
    commands:
      - echo Build started...
      - cd ../
      - npm run test
artifacts:
  files:
    - '**/*'
  base-directory: .