version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd server
      - npm install
      - npm install @nestjs/mongoose mongoose
      - cd ../client
      - npm install
      - npm install axios
  build:
    commands:
      - echo Build started...
artifacts:
  files:
    - '**/*'
  base-directory: .